### ISSUE TITLE
Diagonal problem

### ISSUE THREAD

**Issue by OnePencli** [emranemon/cppvisgraph#1]
Thank you for your project.But I have a problem,In the constructor of your Graph class, you use two adjacent points of a polygon to form an edge. In this case, if the order of the vertices of the input polygon is different during use, will the diagonal of the polygon be mistaken for an edge. For example, if the vertex coordinates of a quadrilateral are (1,1), (4,1), (2,2), (5,2), and I input them in the order of (1,1), (2,2), (5,2), and (4,1), it may not seem like a problem, but when the order becomes (1,1), (4,1), (2,2), and (5,2), the system may mistake the diagonal for the edge of the quadrilateral, which may cause problems.

**Comment by emranemon** [comment]
Thank you for the in-depth look at my source and appreciate your valuable feedback. Just for a quick insight, my implementation is not something unique, it is just an identical translation of the original python lib [pyvisgraph](https://github.com/TaipanRex/pyvisgraph/).

About the issue itself, you are not expected to enter the list of points in such way. Either the point will be clockwise or counter clockwise. In your case, it is valid either  [(1,1), (4,1), (5,2), (2,2)] or [(1,1), (2,2), (5,2), (4,1)]. The original graph constructor [pyvisgraph/graph.py](https://github.com/TaipanRex/pyvisgraph/blob/master/pyvisgraph/graph.py) says and I quote

> The input must be a list of polygons, where each polygon is a list of
    in-order (clockwise or counter clockwise) Points. 

If you are not sure about your input (points in a polygon) are in such order, you may need to sort it before you pass it to the `void build(const std::vector<std::vector<Point>>& input ............)` . To do so, you may follow [stackoverflow-sort-points-in-clockwise-order](https://stackoverflow.com/questions/6989100/sort-points-in-clockwise-order)

If your problem is solved, you can close the issue.
Thank you.

**Comment by OnePencli** [comment]
Thank you for your patient answer. I understand what you mean. Based on your answer, it seems that I can see the order of the required input points as something similar to a communication protocol.


In summary, thank you for your response. I will close this issue,but I think you can simply leave a comment in the source code so that future users have similar problems. Thank you very much





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "emranemon/cppvisgraph"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月2日(星期四) 下午2:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [emranemon/cppvisgraph] Diagonal problem (Issue #1)





 
Thank you for the in-depth look at my source and appreciate your valuable feedback. Just for a quick insight, my implementation is not something unique, it is just an identical translation of the original python lib pyvisgraph.
 
About the issue itself, you are not expected to enter the list of points in such way. Either the point will be clockwise or counter clockwise. In your case, it is valid either  [(1,1), (4,1), (5,2), (2,2)] or [(1,1), (2,2), (5,2), (4,1)]. The original graph constructor pyvisgraph/graph.py says and I quote
  
The input must be a list of polygons, where each polygon is a list of
 in-order (clockwise or counter clockwise) Points.
  
If you are not sure about your input (points in a polygon) are in such order, you may need to sort it before you pass it to the void build(const std::vector<std::vector<Point&gt;&gt;&amp; input ............) . To do so, you may follow stackoverflow-sort-points-in-clockwise-order
 
If your problem is solved, you can close the issue.
 Thank you.
